# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.paint_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.paint_btn.setGeometry(QtCore.QRect(20, 490, 93, 28))
        self.paint_btn.setObjectName("paint_btn")
        self.axiom = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.axiom.setGeometry(QtCore.QRect(10, 40, 113, 22))
        self.axiom.setObjectName("axiom")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 310, 111, 16))
        self.label_3.setObjectName("label_3")
        self.recursion_depth = QtWidgets.QComboBox(parent=self.centralwidget)
        self.recursion_depth.setEnabled(True)
        self.recursion_depth.setGeometry(QtCore.QRect(10, 340, 73, 22))
        self.recursion_depth.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.recursion_depth.setObjectName("recursion_depth")
        self.degrees = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.degrees.setGeometry(QtCore.QRect(20, 390, 113, 22))
        self.degrees.setObjectName("degrees")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 370, 231, 16))
        self.label_4.setObjectName("label_4")
        self.theorems = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.theorems.setGeometry(QtCore.QRect(10, 100, 211, 181))
        self.theorems.setObjectName("theorems")
        self.error_mess = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_mess.setGeometry(QtCore.QRect(270, 210, 471, 81))
        self.error_mess.setText("")
        self.error_mess.setObjectName("error_mess")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(490, 20, 481, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.index_fr = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.index_fr.setGeometry(QtCore.QRect(320, 380, 113, 22))
        self.index_fr.setObjectName("index_fr")
        self.rec_dep = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.rec_dep.setGeometry(QtCore.QRect(320, 430, 113, 22))
        self.rec_dep.setObjectName("rec_dep")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 360, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 410, 161, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.paint_btn.setText(_translate("MainWindow", "Рисовать"))
        self.label.setText(_translate("MainWindow", "Аксиома:"))
        self.label_2.setText(_translate("MainWindow", "Теоремы:"))
        self.label_3.setText(_translate("MainWindow", "Глубина Рекурсии"))
        self.label_4.setText(_translate("MainWindow", "На сколько частей делится плоскость"))
        self.label_5.setText(_translate("MainWindow", "Введите индекс"))
        self.label_6.setText(_translate("MainWindow", "Введите глубину рекурсии"))
